---
title: "create voxel data with NAs for testing"
author: "Chenying Zhao"
output: html_document
---

This is to create voxel data with NAs (e.g. subject-specific mask) for CircleCI testing for ModelArray.\
WARNING: this is not generated by ConVoxel, so there could be inconsistency between ConVoxel's generated .h5 file vs this one. Here we're mainly targeting for values in the scalar matrix.
```{r libraries, include = FALSE}
rm(list=ls())
library(ModelArray)
library(rhdf5)
library(hdf5r)
library(testthat)
set.seed(5)
```

```{r create h5}
nsubj <- 60    # 30 (for all NAs!!!), 40, 60 (because 50*relative_thr = 50*20% = 10 = absolute_thr)
nvoxels <- 100
dim <- c(10,10,10)
scalar_name <- "FA"

if (nsubj == 30) {
  list.num.valid.subj <- rep(0, nvoxels)
} else {
  list.num.valid.subj <- c(rep(0, 10),  # first 10 voxels: NaNs
                         c(0.3*nsubj, 0.2*nsubj, 0.1*nsubj,
                            12, 10, 8),
                         rep(nsubj, 4),    # #11-20: for testing
                         rep(nsubj, 30-1),   # #21-49: good
                         rep(0, 11),    # #50-60: NaNs
                         rep(nsubj, 40))   # rest: good
}

expect_equal(length(list.num.valid.subj),
             nvoxels)

num.subj.lthr.abs <- 10
num.subj.lthr.rel <- 0.2

# the h5 file to create
folder.h5 <- "/home/chenying/Desktop/fixel_project/data/data_forCircleCI_voxeldata_wNAs"
if (nsubj==30) {
  fn.h5 <- file.path(folder.h5, 
                   paste0("n", toString(nsubj), "_voxels_allInvalidValues.h5"))
} else {
  fn.h5 <- file.path(folder.h5, 
                   paste0("n", toString(nsubj), "_voxels.h5"))
}

fn.csv <- gsub(".h5", ".csv", fn.h5)
fn.expectedResults <- gsub(".h5", "_expectedResults.txt", fn.h5)

```

```{r expect test results}
# whether there are sufficient subjects; if so = 1, if not = NA
list.index.voxel.insufficient <- c()
list.results <- rep(NULL, nvoxels)
for (i in 1:length(list.num.valid.subj)) {
  num.valid.subjects <- list.num.valid.subj[i]
  if ((num.valid.subjects > num.subj.lthr.abs) & (num.valid.subjects > num.subj.lthr.rel * nsubj)) {   # both are "greater than" ">"
    list.results[i] <- 1
  } else {
    list.index.voxel.insufficient <- c(list.index.voxel.insufficient,
                                       i)
    list.results[i] <- 0
  }
}
list.index.voxel.insufficient
# save list.results:
list.results <- data.frame(flag_sufficient_subj = list.results)
write.table(list.results, file=fn.expectedResults, sep=",", row.names=FALSE, col.names=TRUE, quote = FALSE)  

```

```{r create companion csv file}
list.age <- runif(nsubj, min = 10, max = 20)
df.csv <- data.frame(subjid =  paste("subj", as.character(1:nsubj), sep=""),
                     age = list.age, 
                     sex = sample(1:2, nsubj, replace = TRUE),   # integer 1 or 2
                     factorA = list.age + runif(nsubj, min = -1, max = 1),   # correlated with age
                     source_file = paste("FA/subj", as.character(1:nsubj), ".nii.gz", sep=""),
                     source_mask_file = paste("FA/subj", as.character(1:nsubj), "_mask.nii.gz", sep=""))
write.table(df.csv, file=fn.csv, sep=",", row.names=FALSE, col.names=TRUE, quote = FALSE)  
```

```{r create the h5 file}
if (file.exists(fn.h5)) {
  file.remove(fn.h5)   # remove existing one
}
h5 <- hdf5r::H5File$new(fn.h5, mode="a")
```

```{r create group voxels}
voxels <- cbind(0:(nvoxels-1),   # voxel_id, starting from 0
                rep(5, nvoxels),   # assume it's on the same x slice
                rep(1:10, nvoxels/10),    # 1,2,....10, 1,2,...10,...
                rep(1:10, each = nvoxels/10))   # 1,1,1,1,...,2,2,2,.....
mode(voxels) <- "integer"   # convert into integer
h5[["voxels"]] <- voxels
```

```{r create group scalars}
# scalars:
scalars.grp <- h5$create_group("scalars")
thescalar.grp <- scalars.grp$create_group(scalar_name)


for (i in 1:length(list.num.valid.subj)) {
  expect_lte(list.num.valid.subj[i], nsubj)
}

# generate scalar_mat based on list.num.valid.subj (for first several voxels):
scalar_mat <- matrix(rep(0, nvoxels * nsubj),
                     nrow = nvoxels,
                     ncol = nsubj)
for (i in 1:length(list.num.valid.subj)) {
  num.valid.subj <- list.num.valid.subj[i]
  if (num.valid.subj == 0) {
    if (i%%3 == 0) {    # if the row number (i.e. voxel id) is 3 times x
      toadd <- rep(Inf, nsubj)
    } else if (i%%3 == 1) {
      toadd <- rep(NaN, nsubj)    # this is possible with ConVoxel
    } else if (i%%3 == 2) {
      toadd <- rep(NA, nsubj)    # note: is.finite(NA) = FALSE (find, that's how ModelArray runs); but is.nan(NA) is FALSE too!!! i.e. NA isn't considered as NaN in R!!
    }
    
  } else {
    toadd <- c(runif(num.valid.subj),     # random number between 0-1, #=listed in the list
             rep(NaN,  (nsubj - num.valid.subj)  ))    # the rest = NaN
  }
  
  rownames(toadd) <- NULL
  scalar_mat[i, ] <- toadd
  
}
rownames(scalar_mat) <- NULL

thescalar.grp[["values"]] <- scalar_mat


# add source filenames as the column_names:
list.source_file <- paste("FA/subj", as.character(1:nsubj), ".nii.gz", sep="") 
hdf5r::h5attr(thescalar.grp[["values"]], "column_names") <- list.source_file

h5$close_all()

h5ls(fn.h5)
```

