---
title: "demo for ModelArray.gam()"
output: html_document
---
```{r}
# set ups
rm(list = ls())
relative_path_ModelArray <- "../../ModelArray"
relative_path_data <- "../../data"

# the working directory of this Demo is where it locates

flag_library_what <- "automatically"   # "automatically" or "manually"

if (flag_library_what == "automatically") {
  message("Please make sure that github repository 'ModelArray' has been updated: local files have been pushed!")
  message("run: devtools::install_github() to install ModelArray package")
  library(devtools)
  devtools::install_github("PennLINC/ModelArray",
                           upgrade = "never")   # not to upgrade pacakge dependencies
  library(ModelArray)
  
  library(tictoc)
  
} else if (flag_library_what == "manually") {
  
  message("run: source several R scripts and library some R packages...")

  source(file.path(relative_path_ModelArray, "R/ModelArray_Constructor.R"))
  source(file.path(relative_path_ModelArray, "R/ModelArray_S4Methods.R"))
  source(file.path(relative_path_ModelArray, "R/utils.R"))
  source(file.path(relative_path_ModelArray, "R/analyse.R"))
  # library(ModelArray)
  suppressMessages(library(dplyr))
  library(broom)
  library(hdf5r)
  library(tictoc)
  library(mgcv)
  # library(lineprof)
  # library(profvis)
  # library(peakRAM)
  suppressMessages(library(doParallel))
}


flag_whichdataset <- "test_n25x2"   # "test_n50" or "test_n25x2" or "josiane"
num.subj <- 25  # [integer]     # 25 for "test_n25x2"
num.fixels <- 100  # 0 = full 
flag_which_subset <- ""
flag_where <- "vmware"   # "CUBIC" or "vmware"


```

# Inputs set-ups: copy the input .h5 file and name it as fn.output; 
```{r}
now_str <- format(Sys.time(), "%Y%m%d-%H%M%S")

if (flag_whichdataset == "test_n50") {
  fn <- file.path(relative_path_ModelArray,"inst/extdata/n50_fixels.h5")
  
  if (flag_where == "CUBIC") {
    fn.output <- "../../dropbox/data_forCircleCI_n50/n50_fixels_output.h5"
  } else if (flag_where == "vmware") {
    fn.output <- "/home/chenying/Desktop/fixel_project/data/data_forCircleCI_n50/n50_fixels_output.h5"  
    # absoluate path: "/home/chenying/Desktop/fixel_project/data/data_forCircleCI_n50/n50_fixels_output.h5";  
    # relative path: "../../data/data_forCircleCI_n50/n50_fixels_output.h5"
  }
  
  fn_csv <- file.path(relative_path_ModelArray, "inst/extdata/n50_cohort.csv")
  
  scalar = c("FD")
  
} else if (flag_whichdataset == "test_n25x2") {
  fn <- file.path(relative_path_data, "data_forCircleCI_n25x2", "fixels_withSubjID.h5")
  fn.output <- file.path(relative_path_data, "data_forCircleCI_n25x2", "fixels_withSubjID_output.h5")
  fn_csv <- file.path(relative_path_data, "data_forCircleCI_n25x2", "n25x2_cohort.csv")
  scalar_all <- c("FD","FD_fake")  
  scalar <- "FD_fake"
  
} else if (flag_whichdataset == "josiane") {
  if (flag_where == "vmware") {
    fn <- paste0("../../data/data_from_josiane/ltn_FDC_n", toString(num.subj), ".h5")
    fn.output <-  paste0("../../data/data_from_josiane/results/ltn_FDC_n", toString(num.subj), "_wResults_nfixel-",toString(num.fixels), "_",now_str, ".h5")
    fn_csv <- paste0("../../data/data_from_josiane/df_example_n", toString(num.subj), ".csv")
    
  }

  scalar <- c("FDC")
}


# generate fn.output:
if (fn != fn.output) {
  file.copy(from=fn, to=fn.output, overwrite = TRUE, copy.mode = TRUE, copy.date = TRUE)   # , recursive = TRUE
}

# h5closeAll()
modelarray <- ModelArray(fn.output, scalar_types = scalar)

```


A quick overview of this ModelArray object:
```{r}
modelarray
scalars(modelarray)[[scalar]]

# check # subjects matches:
if (dim(scalars(modelarray)[[scalar]])[2] != num.subj) {
  stop(paste0("number of subjects in .h5 = ", dim(scalars(modelarray)[[scalar]])[2], ", is not equal to entered number = ", toString(num.subj)))
}
```

We set up for performing GAM:
```{r}
phenotypes <- read.csv(fn_csv)
if (flag_whichdataset == "test_n25x2") {
  # filter phenotypes data.frame for only one scalar:
  phenotypes <- phenotypes[phenotypes$scalar_name == scalar,]
}


# check # subjects matches:
if (nrow(phenotypes) != num.subj) {
  stop(paste0("number of subjects in .csv = ", toString(nrow(phenotypes)), ", is not equal to entered number = ", toString(num.subj)))
}

if (flag_whichdataset == "test_n50") {
  formula <- FD ~ s(age, k=4, fx=TRUE) + sex        # ++++ to do: add motion quantification   # FD ~ s(age, k=4) + sex  # FD ~ s(age) + sex
} else if (flag_whichdataset == "test_n25x2") {
  formula <- as.formula(paste0(scalar, "~ s(age, k=4, fx=TRUE) + sex"))
} else if (flag_whichdataset == "josiane") {
  formula <- FDC ~ s(Age, k=4, fx = TRUE) + sex
}

if (num.fixels == 0) {
  num.fixels <- dim(scalars(modelarray)[[scalar]])[1]
}
element.subset <- 1:num.fixels  
```

# Start to run ModelArray.gam():
```{r}
cat("formula is: ")   
formula
cat(paste0("number of fixels to analyze = ", toString(num.fixels), "\n"))

# defaults:
mygam <- ModelArray.gam(formula = formula, data = modelarray, phenotypes = phenotypes, scalar = scalar, 
                           element.subset = element.subset, 
                        eff.size.term.index = c(1),  
                        n_cores=2, pbar = TRUE)
mygam[1:6, ]
print("column names of returned dataframe:")
colnames(mygam)
```

# full.outputs = TRUE:
```{r}
mygam_allOutputs <- ModelArray.gam(formula = formula, data = modelarray, phenotypes = phenotypes, scalar = scalar, 
                           element.subset = element.subset, 
                           full.outputs = TRUE,
                        eff.size.term.index = c(1),   # eff.size's request is separated from full.outputs (user may not know it may run for an unexpected long time)
                        correct.p.value.smoothTerms = c("fdr", "bonferroni"),   # this is also separated from full.outputs
                        correct.p.value.parametricTerms = c("fdr", "bonferroni"),
                        n_cores=2, pbar = TRUE)
mygam_allOutputs[1:6, ]
print("column names of returned dataframe:")
colnames(mygam_allOutputs)
# write:
analysis_name <- "gam_allOutputs"
writeResults(fn.output, df.output = mygam_allOutputs, analysis_name=analysis_name, overwrite=TRUE)

# # you can write another analysis:
# analysis_name_another <- "gam_allOutputs_duplicated"
# writeResults(fn.output, df.output = mygam_allOutputs, analysis_name=analysis_name_another, overwrite=TRUE)


# # read and see
modelarray_new <- ModelArray(fn.output, scalar_types = scalar, analysis_names = c(analysis_name))
modelarray_new@results$gam_allOutputs

# modelarray_new <- ModelArray(fn.output, scalar_types = scalar, analysis_names = c(analysis_name,analysis_name_another))
# modelarray_new@results[[analysis_name_another]]

```
# check out the results of PNC dataset
```{r}
cat("formula for PNC's dataset: ")
FDC ~ s(Age, k = 4, fx = TRUE) + sex
cat("used default method='GCV.Cp' \n")
cat("time needed: nearly 9h (including another run of reduced model without smooth term); requested ncores=4 (4 child processes), but all 8 CPU cores were in,  \n")
# time required: 
# 
fn.josiane.full <- "/home/chenying/Desktop/fixel_project/data/data_from_josiane/results/ltn_FDC_n938_wResults_nfixel-0_20211126-182543.h5"
modelarray_josiane_full <- ModelArray(fn.josiane.full, scalar_types = c("FDC"), analysis_names = "gam_allOutputs")
modelarray_josiane_full@results$gam_allOutputs$results_matrix 
colnames(modelarray_josiane_full@results$gam_allOutputs$results_matrix )

```

# Play around with mgcv::gam() - blocks in analyseOneGrid.gam()
```{r}

i_grid <- 1
values <- scalars(modelarray)[[scalar]][i_grid,]
dat <- phenotypes
dat[[scalar]] <- values


gam.method = "REML"   # "GCV.Cp", "REML"  # any other methods usually used?
gam.optimizer = c("outer","newton")   # default: c("outer","newton") | # number of optimizers here will not change number of rows or columns in output gam model


onemodel <- mgcv::gam(formula, data = dat,
                      method = gam.method,
                      optimizer = gam.optimizer)   # output of gam: see gamObject
onemodel.summary <- summary(onemodel)

onemodel.tidy.smoothTerms <- onemodel %>% broom::tidy()   #  !!! if formula is FD ~ age without s(), onemodel.tidy.smoothTerm will be empty....
onemodel.tidy.parametricTerms <- onemodel %>% broom::tidy(parametric = TRUE)  # different column names from .smoothTerm....

onemodel.glance <- onemodel %>% broom::glance()



onemodel.tidy.smoothTerms
onemodel.tidy.parametricTerms
onemodel.glance
onemodel.summary

# last two rows of output of summary():
onemodel.summary$r.sq   # adjusted r square
onemodel.summary$dev.expl   # Deviance explained
onemodel.summary$sp.criterion    # e.g. GCV when method is GCV    # test out other methods!  # [["GCV.Cp"]]
onemodel.summary$scale   # Scale est.

# for those values in summary() but not appear in onemodel.tidy or glance: see onemodel.summary and documentations of summary.gam()
# how to get the last two rows in summary(onemodel)? e.g. GCV (maybe other name), R-sq.(adj)

```



# Test out getting formula for reduced model
```{r}
full.formula <- FD ~ s(age, k=4) + s(sex)
ttt <- terms(full.formula, keep.order = TRUE)   # not the re-order the terms | see: https://rdrr.io/r/stats/terms.formula.html
ttt %>% attr(which = "term.labels")   # attributes: see ?terms.object
# or:
labels(ttt)
ttt

# drop terms:
i_term <- 1
print("reduced formula:")
reduced.formula <- drop.terms(ttt, i_term, keep.response = TRUE)
reduced.formula
```

# Example from terms(), terms.object, and drop.terms()
```{r}
ff <- y ~ z + x + w
tt <- terms(ff)
#tt
drop.terms(tt, 2:3, keep.response = TRUE)   # this could be used as a new formula
# tt[-1]
# tt[2:3]
# reformulate(attr(tt, "term.labels"))
# 
# 
# all.vars(ff[-2])   # extract the term names (without transform such as s); [-2] means excluding LHS of the formula
```




