---
title: "prepare walkthru data"
author: "Chenying Zhao"
output: html_document
---
```{r general setups}
# PLEASE RUN THIS CHUNK FIRST!
rm(list=ls())
nsubj <- 100

library(dplyr)
library(testthat)
library(openssl)
set.seed(5)

folder.demo <- "/home/chenying/Desktop/myProject"
folder.nottoshare <- "/home/chenying/Desktop/myProject/NOT_TO_SHARE"
fn.strat.sample <- file.path(folder.nottoshare, 
                             paste0("stratified_wbblid_n",toString(nsubj), ".csv"))
fn.csv.demo <- file.path(folder.demo, 
                         paste0("cohort_FDC_n",toString(nsubj),".csv"))
```

```{r stratify the samples}
# ++++++++++++++=
nall <- 938
# +++++++++++++++

# load the original n=938 subjects:
fn.csv.all <- paste0("/home/chenying/Desktop/fixel_project/data/data_from_josiane/df_example_n",toString(nall),".csv")
csv.all <- read.csv(fn.csv.all)
expect_equal(nrow(csv.all), nall)

# create age bins:  # ref: https://community.rstudio.com/t/dplyr-way-s-and-base-r-way-s-of-creating-age-group-from-age/89226/2
csv.all <- csv.all %>% 
  mutate(
    # Create categories
    Age_group = dplyr::case_when(
      Age < 9              ~ "8-9",
      Age >= 9 & Age < 10  ~ "9-10",
      Age >= 10 & Age < 11 ~ "10-11",
      Age >= 11 & Age < 12 ~ "11-12",
      Age >= 12 & Age < 13 ~ "12-13",
      Age >= 13 & Age < 14 ~ "13-14",
      Age >= 14 & Age < 15 ~ "14-15",
      Age >= 15 & Age < 16 ~ "15-16",
      Age >= 16 & Age < 17 ~ "16-17",
      Age >= 17 & Age < 18 ~ "17-18",
      Age >= 18 & Age < 19 ~ "18-19",
      Age >= 19 & Age < 20 ~ "19-20",
      Age >= 20 & Age < 21 ~ "20-21",
      Age >= 21 & Age < 22 ~ "21-22",
      Age >= 22            ~ ">=22",
    ),
    # Convert to factor
    Age_group = factor(
      Age_group,
      level = c("8-9",
                "9-10",
                "10-11",
                "11-12",
                "12-13",
                "13-14",
                "14-15",
                "15-16",
                "16-17",
                "17-18",
                "18-19",
                "19-20",
                "20-21",
                "21-22",
                ">=22")
    ),
    .after="Age"
  )


strat_sample <- csv.all %>%
                  group_by(Age_group) %>%
                  sample_frac(size=nsubj/938)
hist(strat_sample$Age, breaks=16)

# remove unnecessary columns e.g. behaviors:
strat_sample <- strat_sample %>% ungroup()    # remove group_by
strat_sample <- strat_sample %>%  select(c("bblid","sex","Age","dti64MeanRelRMS",
                                          "scalar_name"))
# # add the source_file column:
# strat_sample <- strat_sample %>% mutate(source_file = paste0("FDC/sub-", bblid, ".mif"))

# expect bblids are unique:
expect_equal(strat_sample$bblid %>% unique() %>% length,
             nrow(strat_sample))

# save:
write.csv(strat_sample, file = fn.strat.sample, row.names = FALSE)
```

```{r hash pnc bblid}
source(file.path(folder.nottoshare,"key_for_hash_pnc.txt"))   # get "key_for_hash"
strat_sample <- read.csv(fn.strat.sample)

list.bblid <- strat_sample$bblid %>% as.character()   # change to character

# sha256, using a key, and taking the first 7 characters:
strat_sample$subject_id <- paste("sub-",
                                 substr(sha256(list.bblid, key=key_for_hash), 1,7),
                                 sep="")

# check if they are unique:
expect_equal(strat_sample$subject_id %>% unique() %>% length(),
             nsubj)

# add the source_file column:
strat_sample <- strat_sample %>% mutate(source_file = paste0("FDC/", subject_id, ".mif"))

# only select the columns needed by the demo:
csv.demo <- strat_sample %>% select(c("subject_id", "Age", "sex","dti64MeanRelRMS",
                                      "scalar_name","source_file"))

# save:
write.csv(csv.demo, file = fn.csv.demo, row.names = FALSE)
# also update strat_sample with hashed id (overwrite it):
write.csv(strat_sample, file = fn.strat.sample, row.names = FALSE)
```


```{r copy input mif files}
# prepare walk-thru original data (before sending to ConFixel)
# because the id has been changed, filename will also be changed when copying

folder_to= file.path(folder.demo, "FDC")
folder_from="/home/chenying/Desktop/fixel_project/data/data_from_josiane/FDC/fdc_10_smoothed_10fwhm_new"

dir.create(folder_to)

# copy index.mif and directions.mif:
fn_from = file.path(folder_from, "index.mif")
file.copy(fn_from, folder_to)

fn_from = file.path(folder_from, "directions.mif")
file.copy(fn_from, folder_to)

## copy data into a folder
# read in .csv file that contains both bblid and hashed id:
strat_sample <- read.csv(fn.strat.sample)
expect_equal(strat_sample %>% nrow(),
            nsubj)

for (i in 1:nrow(strat_sample)) {
  fn_from <- paste(folder_from, "/sub-", strat_sample$bblid[i], ".mif", sep="")
  fn_to <- file.path(folder_to, 
                     paste0(strat_sample$subject_id[i],".mif"))
  expect_true(file.copy(fn_from, fn_to))   # copy, and expect it's true
}


```