---
title: "walk through"
author: "Chenying Zhao"
output: html_document
---

This is to get the printed messages for walk-through docs for ModelArray
THIS FILE SHOULD BE RUN UNDER CONDA ENV "modelarray_paper" TO GET THE CORRECT VERSION OF MODELARRAY AND LIST OF LIBRARIES!
```{r, echo=FALSE}
rm(list=ls())

library(devtools)
library(knitr)   # for kable()
```

```{r}
message(".libPaths():")
.libPaths()   # expect: a folder in conda env

source("../config_global.txt")  # get ModelArray_commitSHA

devtools::install_github(paste0("PennLINC/ModelArray@", ModelArray_commitSHA),
                           upgrade = "never",   # not to upgrade package dependencies
                           force=FALSE)   # force re-install ModelArray again or not
library(ModelArray)
```


```{r display csv file}
# filename of example fixel data (.h5 file):
csv_path <- "~/Desktop/myProject/cohort_FDC_n100.csv"
# load the CSV file:
phenotypes <- read.csv(csv_path)
# let's check the first 3 rows:
head(phenotypes,4)
kable(head(phenotypes,4), format = "markdown", 
      align="c",    # align: center
      digits=c(1, 2, 1, 6, 1, 1)) 
min(phenotypes$Age)
max(phenotypes$Age)
```


```{r create ModelArray object}
# filename of example fixel data (.h5 file):
h5_path <- "~/Desktop/myProject/demo_FDC_n100.h5"
# create a ModelArray-class object:
modelarray <- ModelArray(h5_path, scalar_types = c("FDC")) 
# let's check what's in it:
modelarray 
```

```{r access slots}
# scalar FDC data:
scalars(modelarray)[["FDC"]]
```

```{r example lm}
# formula:
formula.lm <- FDC ~ Age + sex + dti64MeanRelRMS
# run linear model fitting with ModelArray.lm() on the first 100 fixels:
mylm.try <- ModelArray.lm(formula.lm, modelarray, phenotypes, "FDC",
                          element.subset = 1:100)
# let's check the first 6 rows of the results:
head(mylm.try)
head(mylm.try) %>% kable(format = "markdown", 
                        align="c")    # align: center
```


```{r example gam}
# formula:
formula.gam <- FDC ~ s(Age, k=4) + sex + dti64MeanRelRMS
# run GAM fitting with ModelArray.gam() on the first 100 fixels:
mygam.try <- ModelArray.gam(formula.gam, modelarray, phenotypes, "FDC",
                            element.subset = 1:100,
                            correct.p.value.smoothTerms = c("fdr", "bonferroni"),
                            correct.p.value.parametricTerms = c("fdr", "bonferroni"),
                            method="REML")
head(mygam.try)
head(mygam.try) %>% kable(format = "markdown", 
                          align="c")  # align: center
```

```{r inside the full run results}
date_fullrun <- "20220512-213911"
h5_path_new <- paste0("~/Desktop/myProject/demo_FDC_n100_wResults_nfixels-0_",
                      date_fullrun, ".h5")      # THIS IS FILENAME ONLY FOR PRINTING-OUT, NOT TO SHOW UP IN DEMO!
modelarray_new <- ModelArray(filepath = h5_path_new, scalar_types = "FDC",
                             analysis_names = c("results_lm"))
modelarray_new
message("DELETE _wResults_* before .h5!!!")
```

```{r}
results(modelarray_new)[["results_lm"]]$results_matrix
```
